require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - '*.gemspec'
  - 'vendor/**/*'
ClassVars:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  Max: 20
  Exclude:
  - 'app/controllers/enumeration/cli_options.rb'
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Metrics/ClassLength:
  Max: 150
  Exclude:
  - 'app/controllers/enumeration/cli_options.rb'
Metrics/CyclomaticComplexity:
  Max: 8
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
